### ISSUE TITLE
Previous versions returned meta items key as key field

### ISSUE THREAD

**Issue by RensBruil** [plank/laravel-metable#39]
So let me describe this a bit more, as the title says. In previous versions when I returned the collection of a meta collection, it would be as the following:

` "meta" => Illuminate\Database\Eloquent\Collection {#2723 ▼
      #items: array:5[▼

        "source" => Plank\Metable\Meta {#2989 ▶}
        "chamberofcommerce" => Plank\Metable\Meta {#2990 ▶}
        "sbi" => Plank\Metable\Meta {#3551 ▶}
        "telephone" => Plank\Metable\Meta {#3552 ▶}
        "website" => Plank\Metable\Meta {#2727 ▶}
]`

As you can see, the keys are strings which relate to the Meta field 'key'. Now as of version 4.0 (previously 1.1), it is returned as:

` "meta" => Illuminate\Database\Eloquent\Collection {#761 ▼
      #items: array:28 [▼

        0 => Plank\Metable\Meta {#764 ▶}
        1 => Plank\Metable\Meta {#765 ▶}
        2 => Plank\Metable\Meta {#766 ▶}
        3 => Plank\Metable\Meta {#767 ▶}
        4 => Plank\Metable\Meta {#768 ▶}
]`

The meta collection is eager loaded through the model;

`protected $with = ['meta'];`

Any solution for this problem without major changes to the code, in our current project we have alot of links to the key of items in the meta collection.

**Comment by RensBruil** [comment]
The meta collection is eager loaded through the model;

`protected $with = ['meta'];`

**Comment by frasmage** [comment]
Hi there,

The keyed meta collection was an optimization that the package used to optimize access to meta, e.g. O(1) access to a given key rather than O(n) for scanning through the whole collection. However, this indexing of relation collections is non-standard and broke the queueing and serialization of Metable models in more recent versions of Laravel. In order to address this, the package now keeps a separate keyed collection hidden in the background. You can access this with `$metable->getMetaCollection()` to keep operating as you used to.

See [the note at the top of this page](https://laravel-metable.readthedocs.io/en/latest/handling_meta.html) of the documentation for caveats to keep an eye out for.

**Comment by RensBruil** [comment]
What is the best way to implement this in our current model? Currently it is using the eager loaded with method, is there any chance we can change the way it is loaded to use the function that you described?

`protected $with = ['meta'];`

in our model to use `->getMetaCollection()`?

I tried to add the function below;
`public function meta() {
        return $this->getMetaCollection();
    }`

But it will continue to load and returns that the memory is full.

Thanks for your answer, hope to hear from you soon.

**Comment by frasmage** [comment]
Definitely continue to use eager loading of the base relation, but instead of using the meta collection directly, use either the `getMeta($key)`/`setMeta($key, $value) methods to operate on individual keys  or use `getMetaCollection()` if you need to output the dictionary (e.g. for some kind of API response).

If you can a provide more examples of exactly what you were doing with direct access to the underlying relationship, I can point you in the right direction. Do note that the underlying relationship is considered undocumented API, you should always use the methods provided by the package which better encapsulate the desired functionality. If there was some behaviour missing, you can always request a feature or put up your own PR to extend the package.

**Comment by RensBruil** [comment]
While trying to implement the `getMetaCollection()`, the method is undefined and not found. While all other functions are still working, 

The model 'Company' has the following code;
`protected $with = ['meta', 'status'];`

And trying to retrieve meta by the following code in our controller;
`$companies = Company::where('')->get();`
`foreach($companies as $company) {`
`$company->getMetaCollection();`
`}`

The above is not working with the following error;
`Call to undefined method Modules\Relation\Http\Company::getMetaCollection()`

While all other functionalities for retrieving meta are working.

**Comment by RensBruil** [comment]
The collection is returned to an ajax datatable, which reads the meta like the following;
```
return t.company.meta.source;
return t.company.meta.chamberofcommerce; 
```
etc.

This is implemented for all of our models which are linked to some table (my estimation over 25+ tables). So it is pretty huge for us that the keys are like the type so there is no need for a huge code change. Will try your method soon!

Thanks for the information so far.
