### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by Stehos** [plank/laravel-metable#45]
Hi Guys, I just want to ask, if it's good practise to have just one and only table to storage all metas for every model. For example if I will have 80 000 users and 80 000 products and every single user / post will have at least 5 meta stored in the "meta" table then this table will have more then 800 000 rows and I am not sure how fast will be getting required data for the specific user or post.

Also, please could you give me advice, how can I change the name of the table? E.g. change the table name from "meta" to "users_meta" and I do not want to update anything inside the vendor folder

Thank you for your help.

**Comment by frasmage** [comment]
Hi there,

to evaluate performance, you will need to provide more context on what types of operations you are doing. If you all you are doing is attaching meta to models, eager loading the values and using them in the application, then you should have no scaling issues, as the polymorphic foreign key is indexed.

Where you may run into scaling issues is with searches. Value is _not_ indexed. As such, queries that need to compare values, such as `whereMeta()` and `orderByMeta()`, will not operate as efficiently at high scale . If you find that you frequently need to query by certain fields, you will likely be better off storing them a dedicated database column with an index.

There is a note about this in the [query section](https://laravel-metable.readthedocs.io/en/latest/querying_meta.html#a-note-on-optimization) of the docs.

**Comment by frasmage** [comment]
To change the table name, create a subclass of `Meta`, register it in the `metable.model` config, and specify the `$table` property as you would with any other eloquent model.

Note, the library isn't designed to have multiple meta tables (the whole point of the package is attaching anything to anything), you may need to subclass the `Metable` trait to do that, but you are on your own for that.

**Comment by Stehos** [comment]
@frasmage  thank you for your comment. The first answer covers what I had to know, there is no need to use meta in the search which means that it should be fine. 

To the second one, I did it in the way you commented but when I run php artisan migrate, it still creates the table with the old name. 

By "register it in the metable.model config" do you mean the following?

```
<?php

use App\MetaData;

return [
    /*
     * Model class to use for Meta.
     */
    'model' => MetaData::class,
```

My MetaData model:
```
<?php

namespace App;

use Plank\Metable\Meta;

class MetaData extends Meta
{
    protected $table = 'meta_meta';
}

```

Thank you.

**Comment by frasmage** [comment]
Ah, sorry, I assumed that you had already renamed the table. 

Copy the migration files from this package into your application's database migration directory. It is important that you keep the filename identical so that your copy supersedes the package's. You can then modify the table to suit your needs before running migrations. Note: if a future major version of this package contains other schema migrations, you will need to repeat this process in order to rename the tables to match.

**Comment by vesper8** [comment]
@frasmage I have the same concerns, and would love it if you would consider the following for a future iteration of your otherwise very useful package!

I too would like to be able to use multiple meta tables. And I would like it if I could specify that one of these meta tables has the value indexed. This way I could store meta information that is often queried/searchable in that table and store the rest of my meta values in the normal table without an index on value.

If you feel like this is not something you would like to add, then I would appreciate your thoughts on how I may be able to implement such a thing in a fork and what would be the main challenges I would face in doing so

Many thanks for your continued hard work on this package!

**Comment by frasmage** [comment]
Hi there,

Using multiple tables is actually already possible to do with the library as written. You can override the `Metable::getMetaClassName()` to point to a different model which has a different table.

```
class UserMeta extends Meta
{
    protected $table = 'user_meta';
}

class ProductMeta extends Meta
{
    protected $table = 'product_meta';
}

class User extends Model
{
    use Metable;

    protected function getMetaClassName(): string
    {
        return UserMeta::class;
    }
}

class Product extends Model
{
    use Metable;

    protected function getMetaClassName(): string
    {
        return ProductMeta::class;
    }
}

```

As for indexing the value column, that is currently `TEXT` column, which certain engines (e.g. MySQL) aren't great at indexing. You could either change the column type to `VARCHAR`, though that would limit the size of the data you will be able to store without risking truncation, or you can use a prefix index which only accounts for a certain number of characters `CREATE INDEX meta_value ON meta (value(255));` (depending on your query you might be better off with a composite index including the meta_type and/or the key columns).

**Comment by frasmage** [comment]
Included the above in documentation in 5.0.0

**Comment by Stehos** [comment]
> Ah, sorry, I assumed that you had already renamed the table.
> 
> Copy the migration files from this package into your application's database migration directory. It is important that you keep the filename identical so that your copy supersedes the package's. You can then modify the table to suit your needs before running migrations. Note: if a future major version of this package contains other schema migrations, you will need to repeat this process in order to rename the tables to match.

Oooh I didn't see your response. It's working properly. Thank you.

**Comment by vesper8** [comment]
@frasmage Thanks a lot for detailing how to use multiple tables. I'm now using this setup with 3 meta-tables and it's working great
