### ISSUE TITLE
Possible issue?

### ISSUE THREAD

**Issue by DanielLucia** [plank/laravel-metable#68]
Hi, I don't really know if it's a bug ...

I have a table with a million records and the "meta" table has more or less the same. The problem is that the "whereHasMeta" method is extremely slow. Is it a problem with the library that does not manage so many records well?

![Screenshot_481](https://user-images.githubusercontent.com/1748296/144603469-57ccf415-1688-4ef9-bf26-952f8188c482.png)
Thank you.

**Comment by frasmage** [comment]
How many books do you have and how many have the new key?
What indexes do you have applied? can you show your create table syntax for the meta table? 
An `EXPLAIN` of that query (or `EXPLAIN ANALYZE` if you are on mysql >=8.0) would help. Would help to identify if the bottleneck is the meta subquery or the sorting.

Generally speaking though, many of the meta value querying methods are not designed to be used at large scale. Metable is best used to store and retrieve polymorphic/dynamic data. For fields that you need to query against heavily at scale, a dedicated column (with possible index) will be usually be faster. That said, the `key` based query helpers are supposed to reasonably efficient, so we can explore the questions above.

**Comment by DanielLucia** [comment]
First of all, thank you. (And sorry for my English)

I have about 800,000 books, in the "meta" table there are about 2,600,000 records.

These are the two queries.
![imagen](https://user-images.githubusercontent.com/1748296/144706818-49224d4e-073b-46c3-8265-a62fbe645c5e.png)
![imagen](https://user-images.githubusercontent.com/1748296/144706827-03a7407c-d49f-4b9d-9bd9-5c91e421ffa6.png)

Apart from this "problem", I have to admit that this library is incredible. My congratulations to its creator!
Thanks a lot.

**Comment by frasmage** [comment]
Why thank you 😄 

It seems like you have the proper indexing on the Meta table and it is able to look up type/id/key combinations directly.

However, what I am inferring from the explain is that MySQL is using the language/status index on the table first, coming up with over 300k matches, and then loop through each one to match it against the meta table and then again to sort the remainder. 

We are getting outside of the scope of this library, but here are some of my thoughts:

-  If you remove the ORDERBY, I would image it would be a lot faster as it would only need to scan for the first 30 matches against the meta table (your LIMIT), instead of all of them. Subsequent pages naturally get worse if going the OFFSET route.
- I'm not sure how effective that first index is for you, since you are getting nearly half of the table back for these criteria (low cardinality?).
- If you only have a handful of "new" books, you might be better off inverting the query so the dependant subquery gets executed first, e.g. 
  
```SQL
WHERE `books`.`id` IN (
    SELECT `metable`.`metable_id FROM `metable` WHERE `metable`.`metable_type` = 'App\Models\Book' AND `metable`.`key` = 'new'
) AND ...
```

- Alternatively, you can pull that meta key/value into a dedicated column, which might be a little more efficient and could be included in the same index.
