### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by lukasmedia** [plank/laravel-metable#82]
Hi,

I know this could a another problem; but i think it is related to the recordcount in meta since we have 5.121.049 records in that table. The message from MySQL:

Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction (SQL: insert into my-table-meta (key, metable_id, metable_type, type, value) values (somekey, 181308, App\Models\Model, string, 2022-01-29 07:05:55),
on duplicate key update type = values(type), value = values(value)) at file /home/myproject/vendor/laravel/framework/src/Illuminate/Database/Connection.php at line 712

Any thoughts on this?

**Comment by frasmage** [comment]
Hi @lukasmedia,

Deadlocks are a race condition in MySQL when you have multiple concurrent transactions (i.e. different requests) trying to access the same records in different order resulting in an unresolvable loop. For example

Transaction A accesses row 1 (acquires lock)
Transaction B accesses row 2 (acquires lock)
Transaction A accesses row 2 (sleeps waiting for lock to be freed)
Transaction B accesses row 1 (deadlock detected)

This isn't anything specific to this package, it just happens to be a write in the meta table that caused the loop to be detected. 

The best advice I can give you is to try to access data in a deterministic order, e.g. load tables in the same order in different processes to ensure that the concurrent requests try to lock the same rows in the same order, so they wait for each other rather than deadlocking.

**Comment by lukasmedia** [comment]
Thank you for your explanation. In the meantime, I also regularly get the following error:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'App\Models\MyModel-183286-names' for key 'names_meta_metable_type_metable_id_key_unique' (SQL: insert into names-meta (type, value, key, metable_type, metable_id) values

**Comment by lukasmedia** [comment]
Hi,

Please consider this issue done (or just remove it).

I have included meta in a high traffic part of our application. After the necessary refactors, the problems are gone. So no bugs but bad programming.
